# Generated by Django 4.2.2 on 2023-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_batch_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='body_type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
