# Generated by Django 4.2.2 on 2023-06-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_schedule_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
