# Generated by Django 4.2.2 on 2023-07-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_alter_schedule_created_at_alter_schedule_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='critical_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
