# Generated by Django 4.2.2 on 2023-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'ACCEPTED'), (3, 'DELIVERED')], default=1),
        ),
    ]
