# Generated by Django 4.2.2 on 2023-06-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'DELIVERED')], default=0),
        ),
    ]
