# Generated by Django 4.2.2 on 2023-07-13 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0005_request_is_ordered_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
